#! /usr/bin/env python
#
# A small Python-powered script to strip down the IzSound files tree. It wipes
# away the files generated by the autotools framework. These files can be
# generated again later by using the 'bootstrap.sh' script. The CVS (or any
# equivalent) repository should only contain the files left after running a
# 'make distclean' and this script.
#
# IzSound - Copyright (c) 2003, 2004 Julien PONGE - All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import os.path

import sys

# The list of the file names to delete when encountered
names = ["Makefile.in",
         "aclocal.m4",
         "autom4te.cache",
         "config.guess",
         "config.sub",
         "configure",
         "depcomp",
         "install-sh",
         "ltmain.sh",
         "missing",
         "config.h.in",
         "mkinstalldirs"]

# Directory cleaner
def cleanup(path):
  for root, dirs, files in os.walk(path):
    for file in files:
      os.remove(os.path.join(root, file))
  os.removedirs(path)

# The 'main' function
def main():
  start = os.getcwd()
  for root, dirs, files in os.walk(start):
    files.extend(dirs)
    for file in files:
      if (file in names):
        path = os.path.join(root, file)
        if not os.path.exists(path): continue
        if os.path.isdir(path):
          cleanup(path)
        else:
          os.remove(path)

if __name__ == "__main__":
  vers = sys.version_info
  if (vers[0] == 2) and (vers[1] > 2):
    main()
  else:
    print "You need at least Python 2.3 to run this script. Sorry."
